twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
        - 'form/theme.html.twig'

when@test:
    twig:
        strict_variables: true
