hello_index:
    path: /
    controller: App\Controller\HelloController::index

hello_named:
    path: /hello/{name}
    controller: App\Controller\HelloController::named
    defaults:
        name: 'tout-le-monde'
    requirements:
        name: '[a-zA-Z_-]+'

# C'est accessible car format de paramètre distinct
hello_numbered:
    path: /hello/{id}
    controller: App\Controller\HelloController::numbered
    methods: [GET, POST, PUT]
    requirements:
        id: \d+
